// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> fmt_probe_media_file(ffi.Pointer<ffi.Char> path);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void fmt_free_string(ffi.Pointer<ffi.Char> value);
